apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.wordpress.ingress.name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.wordpress.name }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.wordpress.ingress.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.wordpress.name }}
            port: 
              number: {{ .Values.wordpress.service.externalPort }}
  tls:
  - hosts:
    - {{ .Values.wordpress.ingress.host }}
    secretName: wordpress-tls