apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysql.pv.name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ $size := print .Values.mysql.pvc.size "Gi" }}{{ $size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.mysql.pv.path }}"