apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secret.name }}
type: Opaque
data:
  {{ .Values.mysql.secret.password.key }}: {{ .Values.mysql.secret.password.value | b64enc }} 
  {{ .Values.mysql.secret.rootPassword.key }}: {{ .Values.mysql.secret.rootPassword.value | b64enc }} 