apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.config.name }}
  labels:
    app: {{ .Values.mysql.name }}
data:
  {{ .Values.mysql.config.database.key }}: {{ .Values.mysql.config.database.value }}
  {{ .Values.mysql.config.user.key }}: {{ .Values.mysql.config.user.value }}
