apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.wordpress.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /wordpress/$2
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.wordpress.ingress.host }}
    http:
      paths:
      - path: /wordpress(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.wordpress.service.name }}
            port: 
              number: {{ .Values.wordpress.service.externalPort }}