apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: {{ .Values.wordpress.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.wordpress.issuer.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx